<?php
/**********************************************
 *                  turingAdmin.net / PhpStorm
 *   文件名称       :
 *   创建时间       :   2024 年   06 月  05 日 16:00:10
 **********************************************/
namespace turingadmin\annotation;
class Service extends \think\Service
{
    protected  Reader $reader;
    public function boot( Reader $reader) : void
    {
        $this->reader = $reader;
        halt(123);
//        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register(): void
    {
        halt(1234);
//        parent::register(); // TODO: Change the autogenerated stub
    }
}